### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-kj4yz#3]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by KevDCS** [comment]
![Screen Shot 2022-09-20 at 7 46 56 PM](https://user-images.githubusercontent.com/79711202/191328297-94ce74f0-8dd1-4522-b558-7f51a9c7c5fb.png)

The placeholder is now showing in the items that don't have an image.
